#!/usr/bin/env python3
"""AW-21 generated views — the event catalog regenerated from machine-readable seams.

The ecosystem's event catalog used to exist in three uncross-checked hand forms
(bus SPEC.md rows, garden's generated table, the apps-core Rust catalog). This
script makes the declared seams the single authority and REGENERATES the
markdown views from them (arch-R19, descoped to TABLES ONLY):

  1. wicked-core/EVENTS.md                — whole file, fully generated
  2. wicked-bus/reqs/SPEC.md              — ONLY the tables between the
     `BEGIN/END GENERATED EVENT-CATALOG TABLES (AW-21)` markers; every other
     line of SPEC.md is hand-authored and never touched

Declared-vs-emitted drift is computed, not guessed: `--drift` prints the same
report the EVENTS.md drift section embeds (add `--json` for machines).

Seams scanned (all machine-readable; see SEAMS below):
  wicked-core     Rust `pub const X: &str = "wicked...";` declarations + the
                  apps-core `EVENT_CATALOG` array + emit-call windows
                  (`EmitEvent::new(` / `BusEmit::new(` / `.emit(`, non-test)
  wicked-garden   `scripts/_bus.py` BUS_EVENT_MAP (registry) and
                  `scripts/qe/lib/gate.mjs` literals (emit)
  wicked-ledger   `lib/bus-emit.mjs` literals (emit)
  wicked-crew     `packages/crew/src/projects/events.ts` consts (producer) and
                  `packages/crew/src/interactive/*-events.ts` consts (consumer
                  mirrors of wicked-interactive's registry)
  wicked-interactive  `src/service/events.js` EVENT_TYPES (registry) and
                  `src/artifact/{create,publish,validate}.js` literals (emit)

Trigger/payload prose that no seam carries lives in
`event-catalog-annotations.json` next to this script — curated DATA merged into
the generated rows (unknown keys are a hard error so annotations cannot rot).

Modes:
  (default)   regenerate both outputs in place
  --check     regenerate in memory, diff against disk; exit 2 when stale (CI seam)
  --drift     print the declared-vs-emitted / grammar / registry-gap report; exit 0
  --json      with --drift: emit the report as JSON

Python 3 stdlib only; forward-slash paths everywhere (cross-platform mandate).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent  # .../crates/wicked-governance/seed
ANNOTATIONS = HERE / "event-catalog-annotations.json"

# ---------------------------------------------------------------------------
# Grammar (seed corpus: crates/wicked-governance/seed/corpus/event-grammar.md)
# ---------------------------------------------------------------------------
# POL-1801: four-segment wicked.<domain>.<noun>.<past-tense-verb>, WB-001
# pattern /^wicked\.[a-z0-9_]+(\.[a-z0-9_]+)*$/ (no hyphens), exactly 4 segments.
WB001_SEGMENT = re.compile(r"^[a-z0-9_]+$")
# POL-1802: whitelisted producer domains (+ `estate` per AW-22); `test` survives
# only as the legacy-stable QE-lifecycle spelling (domain stamp `qe`).
WHITELISTED_DOMAINS = {"qe", "crew", "garden", "interactive", "estate"}
LEGACY_DOMAINS = {"test"}

# Loose shape used for EXTRACTION so violations are captured (hyphens allowed),
# then flagged by the grammar check rather than silently dropped.
EVENT_LITERAL = re.compile(
    r"""["'](wicked\.[a-z0-9_]+\.[a-z0-9_-]+\.[a-z0-9_-]+)["']"""
)

MARKER_BEGIN = (
    "<!-- BEGIN GENERATED EVENT-CATALOG TABLES (AW-21) — generated by wicked-core "
    "crates/wicked-governance/seed/gen_event_catalog.py; do not hand-edit between "
    "the markers, edit the producing seam or event-catalog-annotations.json and "
    "regenerate -->"
)
MARKER_END = "<!-- END GENERATED EVENT-CATALOG TABLES (AW-21) -->"

REPO_ALIAS = {
    "wicked-core": "core",
    "wicked-garden": "garden",
    "wicked-ledger": "ledger",
    "wicked-crew": "crew",
    "wicked-interactive": "interactive",
}

# (repo, repo-relative path, role, parser)
# role: const    = producer-declared event-type constant
#       registry = machine-readable event registry (the repo's own contract)
#       emit     = literal at an emit call seam
#       mirror   = consumer-side constant mirroring another repo's contract
SEAMS = [
    ("wicked-core", "crates/wicked-apps-core/src/lib.rs", "const", "rust_consts"),
    ("wicked-core", "src/bus.rs", "const", "rust_consts"),
    ("wicked-core", "src/cli_runner.rs", "const", "rust_consts"),
    ("wicked-core", "crates/wicked-orchestration/src/gate.rs", "const", "rust_consts"),
    ("wicked-core", "crates/wicked-governance/src/events.rs", "const", "rust_consts"),
    ("wicked-core", "crates/wicked-governance/src/engine.rs", "const", "rust_consts"),
    ("wicked-garden", "scripts/_bus.py", "registry", "python_map"),
    ("wicked-garden", "scripts/qe/lib/gate.mjs", "emit", "literals"),
    ("wicked-ledger", "lib/bus-emit.mjs", "emit", "literals"),
    ("wicked-crew", "packages/crew/src/projects/events.ts", "const", "ts_consts"),
    ("wicked-crew", "packages/crew/src/interactive/chat-events.ts", "mirror", "ts_consts"),
    ("wicked-crew", "packages/crew/src/interactive/edit-events.ts", "mirror", "ts_consts"),
    ("wicked-crew", "packages/crew/src/interactive/draft-events.ts", "mirror", "ts_consts"),
    ("wicked-crew", "packages/crew/src/interactive/demo-events.ts", "mirror", "ts_consts"),
    ("wicked-interactive", "src/service/events.js", "registry", "js_registry"),
    ("wicked-interactive", "src/artifact/create.js", "emit", "literals"),
    ("wicked-interactive", "src/artifact/publish.js", "emit", "literals"),
    ("wicked-interactive", "src/artifact/validate.js", "emit", "literals"),
]

# Hand-authored heading notes per domain group (curated data, reviewed with the
# script — the ROWS below each heading are generated).
DOMAIN_NOTES = {
    "crew": "engine (wicked-core), crew product lifecycle, and garden's shared phase lifecycle",
    "estate": "governance-corpus lifecycle (wicked-core `wicked-governance`, AW-22)",
    "garden": "wicked-garden registry (`scripts/_bus.py` BUS_EVENT_MAP is the contract)",
    "gate": "governed evaluator round-trip (wicked-core engine)",
    "interactive": "wicked-interactive registry (`src/service/events.js` EVENT_TYPES is the contract)",
    "qe": "QE acceptance gate + lifecycle (garden gate CLI, wicked-ledger)",
    "test": "legacy-stable QE-lifecycle spelling kept at the wicked-testing retirement — the `domain` stamp is `qe`",
}

RUST_CONST = re.compile(
    r'^pub const ([A-Z_][A-Z0-9_]*): &str = "(wicked\.[a-z0-9_.-]+)";', re.M
)
TS_CONST = re.compile(
    r"^export const ([A-Z_][A-Z0-9_]*) = '(wicked\.[a-z0-9_.-]+)';", re.M
)
EMIT_OPENER = re.compile(r"EmitEvent::new\(|BusEmit::new\(|\.emit\(")


def die(msg: str) -> None:
    print(f"gen_event_catalog: error: {msg}", file=sys.stderr)
    sys.exit(1)


def read(ws: Path, repo: str, rel: str) -> str:
    p = ws / repo / rel
    if not p.is_file():
        die(f"seam missing: {p} — run with --workspace pointing at the directory "
            f"that contains the wicked-* checkouts")
    return p.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Parsers — each returns [(event_type, extra)] where extra is a dict
# ---------------------------------------------------------------------------

def parse_rust_consts(text: str):
    out = []
    for m in RUST_CONST.finditer(text):
        line = text.count("\n", 0, m.start()) + 1
        out.append((m.group(2), {"const": m.group(1), "line": line}))
    return out


def parse_ts_consts(text: str):
    out = []
    for m in TS_CONST.finditer(text):
        line = text.count("\n", 0, m.start()) + 1
        out.append((m.group(2), {"const": m.group(1), "line": line}))
    return out


def parse_literals(text: str):
    return [(m.group(1), {}) for m in EVENT_LITERAL.finditer(text)]


def block(text: str, start_re: str, end_re: str, label: str) -> str:
    m = re.search(start_re, text, re.M)
    if not m:
        die(f"cannot find start of {label}")
    e = re.search(end_re, text[m.end():], re.M)
    if not e:
        die(f"cannot find end of {label}")
    return text[m.end(): m.end() + e.start()]


def parse_python_map(text: str):
    """BUS_EVENT_MAP in wicked-garden scripts/_bus.py."""
    body = block(text, r"^BUS_EVENT_MAP: Dict\[str, Dict\[str, str\]\] = \{", r"^\}", "BUS_EVENT_MAP")
    out = []
    entry_re = re.compile(
        r'^    "(wicked\.[a-z0-9_.-]+)": \{\n(.*?)^    \},', re.M | re.S
    )
    for m in entry_re.finditer(body):
        ev, entry = m.group(1), m.group(2)
        desc = re.search(r'"description":\s*"((?:[^"\\]|\\.)*)"', entry)
        dom = re.search(r'"domain":\s*"((?:[^"\\]|\\.)*)"', entry)
        out.append((ev, {
            "description": desc.group(1) if desc else "",
            "domain_stamp": dom.group(1) if dom else "",
        }))
    if not out:
        die("BUS_EVENT_MAP parsed to zero entries — format changed?")
    return out


def parse_js_registry(text: str):
    """EVENT_TYPES in wicked-interactive src/service/events.js."""
    body = block(text, r"^export const EVENT_TYPES = Object\.freeze\(\{", r"^\}\);", "EVENT_TYPES")
    out = []
    entry_re = re.compile(
        r'"(wicked\.[a-z0-9_.-]+)":\s*\{\s*subdomain:\s*"([a-z0-9_]+)",\s*'
        r"owners:\s*\[([A-Z_,\s]+)\],\s*uiEmittable:\s*(true|false)"
    )
    for m in entry_re.finditer(body):
        owners = ", ".join(o.strip().lower() for o in m.group(3).split(","))
        out.append((m.group(1), {
            "description": f"subdomain `{m.group(2)}`; owners: {owners}"
                           + ("; UI-emittable" if m.group(4) == "true" else ""),
        }))
    if not out:
        die("EVENT_TYPES parsed to zero entries — format changed?")
    return out


PARSERS = {
    "rust_consts": parse_rust_consts,
    "ts_consts": parse_ts_consts,
    "literals": parse_literals,
    "python_map": parse_python_map,
    "js_registry": parse_js_registry,
}


def parse_event_catalog_members(text: str) -> list[str]:
    body = block(text, r"^pub const EVENT_CATALOG: &\[&str\] = &\[", r"^\];", "EVENT_CATALOG")
    members = re.findall(r"\b(EV_[A-Z0-9_]+)\b", body)
    if not members:
        die("EVENT_CATALOG parsed to zero members — format changed?")
    return members


# ---------------------------------------------------------------------------
# Core emit-wiring scan (the declared-vs-emitted query)
# ---------------------------------------------------------------------------

def strip_test_tail(text: str) -> str:
    """Drop everything from the first top-level `#[cfg(test)]` to EOF
    (convention in this codebase: the test module is the file's tail)."""
    m = re.search(r"^#\[cfg\(test\)\]", text, re.M)
    return text[: m.start()] if m else text


def scan_core_emit_wiring(ws: Path, consts: dict[str, dict]) -> dict[str, list[str]]:
    """const name -> sorted list of repo-relative files where the const (or its
    literal type) sits within 3 lines of an emit-call opener, outside tests."""
    core = ws / "wicked-core"
    wired: dict[str, set[str]] = {name: set() for name in consts}
    rs_files = sorted(
        p for p in list((core / "src").rglob("*.rs")) + list((core / "crates").rglob("*.rs"))
        if "/tests/" not in p.as_posix() and "/target/" not in p.as_posix()
    )
    for p in rs_files:
        lines = strip_test_tail(p.read_text(encoding="utf-8")).splitlines()
        rel = p.relative_to(core).as_posix()
        opener_ix = [i for i, ln in enumerate(lines) if EMIT_OPENER.search(ln)]
        if not opener_ix:
            continue
        for name, info in consts.items():
            pat = re.compile(rf"\b{name}\b|\"{re.escape(info['type'])}\"")
            for i in opener_ix:
                for j in range(i, min(i + 4, len(lines))):
                    if pat.search(lines[j]):
                        # a const's own declaration line is not an emit seam
                        if rel == info["decl_file"] and j + 1 == info["line"]:
                            continue
                        wired[name].add(rel)
                        break
    return {k: sorted(v) for k, v in wired.items()}


# ---------------------------------------------------------------------------
# Model assembly
# ---------------------------------------------------------------------------

def assemble(ws: Path):
    events: dict[str, dict] = {}
    core_consts: dict[str, dict] = {}

    def ev(t: str) -> dict:
        return events.setdefault(t, {"sources": [], "descriptions": []})

    for repo, rel, role, parser in SEAMS:
        text = read(ws, repo, rel)
        for etype, extra in PARSERS[parser](text):
            e = ev(etype)
            src = (repo, rel, role)
            if src not in e["sources"]:
                e["sources"].append(src)
            if extra.get("description"):
                e["descriptions"].append((repo, extra["description"]))
            if repo == "wicked-core" and "const" in extra:
                core_consts[extra["const"]] = {
                    "type": etype, "decl_file": rel, "line": extra["line"],
                }

    catalog_members = parse_event_catalog_members(
        read(ws, "wicked-core", "crates/wicked-apps-core/src/lib.rs"))
    unknown = [m for m in catalog_members if m not in core_consts]
    if unknown:
        die(f"EVENT_CATALOG members not found as consts: {unknown}")

    wiring = scan_core_emit_wiring(ws, core_consts)

    if ANNOTATIONS.is_file():
        ann = json.loads(ANNOTATIONS.read_text(encoding="utf-8"))
        ann.pop("_comment", None)
    else:
        ann = {}
    stale = sorted(set(ann) - set(events))
    if stale:
        die(f"annotations for unknown event types (edit {ANNOTATIONS.name}): {stale}")

    return events, core_consts, catalog_members, wiring, ann


# ---------------------------------------------------------------------------
# Drift report (query, not guess)
# ---------------------------------------------------------------------------

def grammar_violations(events: dict) -> list[dict]:
    out = []
    for t in sorted(events):
        segs = t.split(".")
        problems = []
        if len(segs) != 4:
            problems.append(f"{len(segs)} segments (grammar requires exactly 4)")
        bad = [s for s in segs[1:] if not WB001_SEGMENT.match(s)]
        if bad:
            problems.append("segment(s) outside WB-001 charset [a-z0-9_]: "
                            + ", ".join(f"`{s}`" for s in bad))
        if len(segs) >= 2 and segs[1] not in WHITELISTED_DOMAINS | LEGACY_DOMAINS:
            problems.append(
                f"producer domain `{segs[1]}` not in the POL-1802 whitelist "
                f"({', '.join(sorted(WHITELISTED_DOMAINS))}; legacy: "
                f"{', '.join(sorted(LEGACY_DOMAINS))})")
        if problems:
            out.append({"event": t, "problems": problems})
    return out


def build_drift(events, core_consts, catalog_members, wiring):
    declared_not_wired = [
        {"const": name, "event": core_consts[name]["type"]}
        for name in catalog_members if not wiring.get(name)
    ]
    wired_outside_catalog = [
        {"const": name, "event": info["type"], "emit_files": wiring[name]}
        for name, info in sorted(core_consts.items())
        if wiring.get(name) and name not in catalog_members
    ]
    emit_only = []
    for t in sorted(events):
        roles = {r for (_, _, r) in events[t]["sources"]}
        if roles == {"emit"}:
            emit_only.append({
                "event": t,
                "emit_files": sorted(f"{repo}:{rel}" for (repo, rel, _) in events[t]["sources"]),
            })
    multi_repo = []
    for t in sorted(events):
        repos = sorted({repo for (repo, _, _) in events[t]["sources"]})
        if len(repos) > 1:
            multi_repo.append({"event": t, "repos": repos})
    return {
        "core_declared_in_EVENT_CATALOG_but_no_emit_seam": declared_not_wired,
        "core_emit_wired_but_outside_EVENT_CATALOG": wired_outside_catalog,
        "emit_seam_only_no_registry_or_const_declaration": emit_only,
        "grammar_violations": grammar_violations(events),
        "declared_in_multiple_repos": multi_repo,
    }


def drift_text(drift: dict) -> str:
    L = []
    L.append("## Declared-vs-emitted drift (computed from the seams — a query, not a guess)")
    L.append("")
    L.append("### Declared in apps-core `EVENT_CATALOG` but no emit seam found (non-test)")
    L.append("")
    rows = drift["core_declared_in_EVENT_CATALOG_but_no_emit_seam"]
    if rows:
        for r in rows:
            L.append(f"- `{r['event']}` (`{r['const']}`)")
    else:
        L.append("- none")
    L.append("")
    L.append("### Emit-wired core constants declared OUTSIDE apps-core `EVENT_CATALOG`")
    L.append("")
    rows = drift["core_emit_wired_but_outside_EVENT_CATALOG"]
    if rows:
        for r in rows:
            L.append(f"- `{r['event']}` (`{r['const']}`) — emitted at "
                     + ", ".join(f"`{f}`" for f in r["emit_files"]))
    else:
        L.append("- none")
    L.append("")
    L.append("### Emit-seam-only types (no registry or const declaration anywhere)")
    L.append("")
    rows = drift["emit_seam_only_no_registry_or_const_declaration"]
    if rows:
        for r in rows:
            L.append(f"- `{r['event']}` — emitted at "
                     + ", ".join(f"`{f}`" for f in r["emit_files"]))
    else:
        L.append("- none")
    L.append("")
    L.append("### Grammar conformance (seed corpus `event-grammar.md`, POL-1801/POL-1802)")
    L.append("")
    rows = drift["grammar_violations"]
    if rows:
        for r in rows:
            L.append(f"- `{r['event']}` — " + "; ".join(r["problems"]))
    else:
        L.append("- none")
    L.append("")
    L.append("### Types with seams in more than one repo (shared contract — informational)")
    L.append("")
    rows = drift["declared_in_multiple_repos"]
    if rows:
        for r in rows:
            L.append(f"- `{r['event']}` — " + ", ".join(r["repos"]))
    else:
        L.append("- none")
    return "\n".join(L)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def src_cell(t: str, sources, core_wired_types: set) -> str:
    parts = []
    for repo, rel, role in sorted(sources):
        tag = role
        if repo == "wicked-core" and role == "const" and t not in core_wired_types:
            tag = "const — **no emit seam**"
        parts.append(f"`{REPO_ALIAS[repo]}:{rel}` ({tag})")
    return "<br>".join(parts)


def notes_for(t: str, events: dict, ann: dict) -> tuple[str, str]:
    a = ann.get(t, {})
    trigger = a.get("trigger", "")
    payload = a.get("payload", "")
    if not trigger:
        descs = events[t]["descriptions"]
        if descs:
            # prefer the owning registry's description; they are already
            # per-repo curated strings
            trigger = descs[0][1]
    return (trigger or "—", payload or "—")


def render_domain_tables(events: dict, ann: dict, core_wired_types: set) -> str:
    by_domain: dict[str, list[str]] = {}
    for t in events:
        by_domain.setdefault(t.split(".")[1], []).append(t)
    L = []
    for dom in sorted(by_domain):
        note = DOMAIN_NOTES.get(dom, "")
        L.append(f"#### `{dom}` events" + (f" — {note}" if note else ""))
        L.append("")
        L.append("| Event type | Declared / emitted at | Trigger / description | Key payload fields |")
        L.append("|---|---|---|---|")
        for t in sorted(by_domain[dom]):
            trigger, payload = notes_for(t, events, ann)
            L.append(f"| `{t}` | {src_cell(t, events[t]['sources'], core_wired_types)} | {trigger} | {payload} |")
        L.append("")
    return "\n".join(L).rstrip("\n")


def core_wired_types(core_consts: dict, wiring: dict) -> set:
    return {info["type"] for name, info in core_consts.items() if wiring.get(name)}


def render_spec_block(events: dict, ann: dict, wired: set) -> str:
    return MARKER_BEGIN + "\n\n" + render_domain_tables(events, ann, wired) + "\n\n" + MARKER_END


def render_events_md(events, core_consts, catalog_members, wiring, ann) -> str:
    L = []
    L.append("# wicked-core event catalog (generated)")
    L.append("")
    L.append("> **GENERATED FILE — do not hand-edit.** Regenerate with")
    L.append("> `python3 crates/wicked-governance/seed/gen_event_catalog.py --workspace <dir containing the wicked-* checkouts>`.")
    L.append("> Rows come from the machine-readable seams listed under \"Seams scanned\";")
    L.append("> trigger/payload prose comes from `crates/wicked-governance/seed/event-catalog-annotations.json`.")
    L.append("> `--check` exits non-zero when this file or the wicked-bus SPEC catalog block is stale;")
    L.append("> `--drift [--json]` prints the drift report below as a standalone query.")
    L.append("")
    L.append("## Core-declared event constants")
    L.append("")
    L.append("| Constant | Event type | Declared at | In apps-core `EVENT_CATALOG` | Emit seam (non-test) |")
    L.append("|---|---|---|---|---|")
    for name in sorted(core_consts):
        info = core_consts[name]
        in_cat = "yes" if name in catalog_members else "no"
        files = wiring.get(name) or []
        emit = ", ".join(f"`{f}`" for f in files) if files else "—"
        L.append(f"| `{name}` | `{info['type']}` | `{info['decl_file']}:{info['line']}` | {in_cat} | {emit} |")
    L.append("")
    L.append("An emit seam is a non-test line referencing the constant (or its literal type)")
    L.append("within 3 lines of `EmitEvent::new(` / `BusEmit::new(` / `.emit(` — the same")
    L.append("window `--drift` queries. \"—\" means no emit seam found in the scanned")
    L.append("wicked-core sources: declared, not emit-wired HERE (an emitter in another repo,")
    L.append("e.g. the requester side of `wicked.crew.run.requested`, is outside this scan).")
    L.append("")
    drift = build_drift(events, core_consts, catalog_members, wiring)
    L.append(drift_text(drift))
    L.append("")
    L.append("## Ecosystem catalog (all domains)")
    L.append("")
    L.append("The same generated tables are published into `wicked-bus/reqs/SPEC.md` §Event")
    L.append("Catalog (between the AW-21 markers) — the bus SPEC remains the reader-facing")
    L.append("home of the catalog; this file is the engine-side view plus the drift report.")
    L.append("")
    L.append(render_domain_tables(events, ann, core_wired_types(core_consts, wiring)))
    L.append("")
    L.append("## Seams scanned")
    L.append("")
    L.append("| Repo | File | Role |")
    L.append("|---|---|---|")
    for repo, rel, role, _parser in SEAMS:
        L.append(f"| {repo} | `{rel}` | {role} |")
    L.append("")
    return "\n".join(L)


def splice_spec(spec_text: str, block_text: str) -> str:
    begin = spec_text.find(MARKER_BEGIN)
    end = spec_text.find(MARKER_END)
    if begin == -1 or end == -1:
        die("wicked-bus/reqs/SPEC.md is missing the AW-21 generated-catalog markers "
            f"({MARKER_BEGIN[:60]}…). Place both markers inside §Event Catalog first.")
    return spec_text[:begin] + block_text + spec_text[end + len(MARKER_END):]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--workspace", type=Path,
                    default=Path(__file__).resolve().parents[4],
                    help="directory containing the wicked-* checkouts "
                         "(default: the parent of this wicked-core checkout)")
    ap.add_argument("--check", action="store_true",
                    help="verify outputs are current; exit 2 when stale")
    ap.add_argument("--drift", action="store_true",
                    help="print the declared-vs-emitted drift report and exit")
    ap.add_argument("--json", action="store_true",
                    help="with --drift: JSON output")
    args = ap.parse_args()

    ws = args.workspace.resolve()
    events, core_consts, catalog_members, wiring, ann = assemble(ws)

    if args.drift:
        drift = build_drift(events, core_consts, catalog_members, wiring)
        if args.json:
            print(json.dumps(drift, indent=2))
        else:
            print(drift_text(drift))
        return 0

    events_md = render_events_md(events, core_consts, catalog_members, wiring, ann)
    spec_path = ws / "wicked-bus" / "reqs" / "SPEC.md"
    if not spec_path.is_file():
        die(f"wicked-bus SPEC not found at {spec_path}")
    spec_new = splice_spec(spec_path.read_text(encoding="utf-8"),
                           render_spec_block(events, ann, core_wired_types(core_consts, wiring)))
    events_path = ws / "wicked-core" / "EVENTS.md"

    if args.check:
        stale = []
        if not events_path.is_file() or events_path.read_text(encoding="utf-8") != events_md:
            stale.append(str(events_path))
        if spec_path.read_text(encoding="utf-8") != spec_new:
            stale.append(f"{spec_path} (generated block)")
        if stale:
            print("STALE generated views (rerun gen_event_catalog.py):")
            for s in stale:
                print(f"  - {s}")
            return 2
        print("generated views current")
        return 0

    events_path.write_text(events_md, encoding="utf-8")
    spec_path.write_text(spec_new, encoding="utf-8")
    print(f"wrote {events_path}")
    print(f"wrote {spec_path} (generated block)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
