/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * WHERE this run's project keeps its co-located code graph, and what this run's repo is called
 * inside it. Set on [`LaunchOptions::project_graph`] by a launcher that owns a project graph.
 *
 * The two fields are one fact and travel together: a path with no label cannot be checked against
 * the repo the run targets, and a label with no path names nothing. Sending them as separate
 * optional fields would make "half-specified" expressible, and the half that goes missing is the
 * one that turns the verification off.
 */
export interface ProjectGraphOptions {
  /** ABSOLUTE path to the project's code graph (crew: `~/.wicked-crew/project-graphs/<id>/code-graph.db`). */
  dbPath: string
  /**
   * The wicked-estate label this run's repo is indexed under in that graph. REQUIRED whenever
   * `repoRef` is set — the engine uses it to confirm the graph actually describes the code the
   * worker will edit, and refuses the binding (falling back to the per-repo graph) when it
   * cannot. Omit only for a repo-less run.
   */
  repoLabel?: string
}
/**
 * Options for [`Core::launch_run`]. `clisJson` is a JSON array of `AgenticCli` seats (the council
 * roster); `Core.registryRoster()` returns the production roster ready to pass here.
 */
export interface LaunchOptions {
  /** The free-text problem to decompose into ordered work units. */
  problem: string
  /** A stable session/run id (empty → the caller must supply one; Core requires an explicit id here). */
  sessionId: string
  /** JSON array of `AgenticCli` seats — the council roster for this run. */
  clisJson: string
  /** `shared` (default) | `isolated` — the collection-scope mode. */
  entityMode?: string
  /** Human-confirm gate policy: `none` (default) | `all` | `before:<ord>`. */
  humanConfirm?: string
  /** The id of a registered repo to run within (creates an isolated worktree). Omit for a repo-less run. */
  repoRef?: string
  /**
   * A registered `WorkflowDef` id (`feature` | `bug` | `migration` or a drop-in). When set, planning
   * is data-driven from the def's phases; omit for the free-text planner.
   */
  workflow?: string
  /**
   * The project to file this run into (DES-PROJECT-001). The `crew.run` membership is attached
   * ATOMICALLY with the launch record (one store batch); an unknown or archived project rejects
   * the launch with no session persisted. Omit for an unfiled run (the synthesized `default`).
   */
  projectId?: string
  /**
   * ADDITIONAL absolute write roots for the run's deliverables (core#259) — e.g. an inbox dir
   * the workflow contract names as the output destination. Widens the governed units'
   * filesystem boundary by exactly these roots, after the unit cwd. Each root must be absolute
   * and outside the engine's config/pin tree — an invalid root REJECTS the launch with no
   * session persisted. Omit for runs that deliver inside their own workdir.
   */
  extraWriteRoots?: Array<string>
  /**
   * The PROJECT code graph this run's governed workers should query, instead of the run repo's
   * own graph — one database holding every member repo of the project, so a worker's
   * SearchEntity / BlastRadius / TraverseGraph can see the whole project rather than one repo.
   *
   * A HINT the engine VERIFIES before any worker sees it: absolute, an existing file, not the
   * engine's own operational store, non-empty, and actually holding `repoLabel`'s repo. A
   * binding that fails any of those degrades the run to the per-repo graph (with a reason on
   * stderr) rather than failing the launch — the graph is a capability, and losing it should
   * cost tools, not the run. Omit for the per-repo behaviour, unchanged.
   */
  projectGraph?: ProjectGraphOptions
}
/**
 * A handle to a wicked-core runtime. Construct with [`Core::spawn`] (production engine: real
 * council + wrapped-CLI subprocesses) or [`Core::spawn_stub`] (deterministic offline engine).
 */
export declare class Core {
  /**
   * Spawn the store actor over the estate db at `path` with the PRODUCTION engine (real council
   * dispatcher + real wrapped-CLI step runner — runs actual agentic CLIs). The actor lives until
   * every handle is dropped.
   */
  static spawn(path: string): Core
  /**
   * Spawn the store actor with the STUB engine — a deterministic council dispatcher +
   * `StubStepRunner`, no subprocesses. For tests / offline runs that must not touch a real LLM.
   */
  static spawnStub(path: string): Core
  /**
   * The production council roster (built-ins ∪ the user's `~/.config/wicked-council/clis.toml`),
   * as a JSON array of `AgenticCli` — pass straight into `launchRun`'s `clisJson`.
   */
  static registryRoster(): string
  /**
   * Subscribe to the live [`CoreEvent`] stream. `callback` follows the Node error-first
   * convention — `(err, eventJson)` — and is invoked once per event with the event serialized as
   * a JSON string (`{ type, ...fields }`); parse it in JS. Events arrive in emission order. Call
   * this BEFORE `launchRun` to catch the whole sequence, and HOLD the returned [`Subscription`]:
   * `close()` / `unsubscribe()` stops delivery and tears the pump thread + callback down.
   *
   * NOTE (ordering): async methods resolve their Promise off a libuv worker thread, while events
   * are delivered from a separate pump thread — so an event emitted by a call MAY be observed by
   * this callback slightly AFTER that call's Promise resolves. Await the event you need (as the
   * smoke does) rather than assuming it precedes the method's resolution.
   */
  subscribe(callback: (err: Error | null, eventJson: string) => void): Subscription
  /** Liveness probe — emits a `Heartbeat` to subscribers and resolves once the actor acks (`"ok"`). */
  ping(): Promise<string>
  /**
   * Open a chat: eagerly warm one ACP session per seat (crew#165 / core#13). Resolves to a
   * JSON array of per-seat outcomes `[{cliKey, ok, error?}]`; `chatSessionReady`/`chatSessionFailed`
   * also stream to subscribers. Blocking handshakes run on the task pool, not the JS thread.
   */
  chatOpen(chatId: string, clisJson: string, cwd?: string | undefined | null): Promise<string>
  /**
   * Fan a message out to the chat's warm seats (all, or `targets_json` subset). Ack-fast:
   * resolves to the JSON array of seats targeted; replies stream as `chatDelta`/`chatReply`.
   */
  chatSend(chatId: string, text: string, targetsJson?: string | undefined | null, cwd?: string | undefined | null): Promise<string>
  /** The seats currently warm for a chat — JSON array of cli keys. */
  chatSeats(chatId: string): Promise<string>
  /**
   * Every chat currently holding pool state — JSON array of
   * `[{chatId, seats, idleSecs}]`, sorted by id.
   *
   * Each warm seat pins an ACP bridge plus an agent child (~520 MB resident) and clients mint
   * chat ids freely, so without this an accumulation is invisible until the host runs out of
   * memory (FINDING-027). `idleSecs` is seconds since the chat's last open/ensure/turn, or
   * `null` when no activity was ever recorded — which the reaper treats as idle-since-forever.
   *
   * `null` rather than the `u64::MAX` the Rust side uses for that case: a JS `number` is an
   * f64, so `u64::MAX` arrives as `18446744073709552000` and no consumer can test for the
   * sentinel by equality. `null` is checkable, and it stops a caller from doing arithmetic on a
   * value that never meant a duration.
   */
  chatList(): Promise<string>
  /**
   * Close a chat's warm sessions (idempotent); emits
   * `chatClosed` with `reason: "requested"`.
   */
  chatClose(chatId: string): Promise<string>
  /**
   * Launch an interactive, resumable run: plans + distributes, then executes each unit off-thread
   * (or pauses at a human-confirm gate). Resolves to the run id. Progress arrives as `CoreEvent`s
   * — `subscribe()` first. Rejects with a busy error if a run with that id is already in flight.
   */
  launchRun(opts: LaunchOptions): Promise<string>
  /**
   * Resume an interactive run from its persisted cursor (after a pause, crash, or fresh process).
   * Resolves to the resulting status token.
   */
  resumeRun(runId: string): Promise<string>
  /**
   * Resolve a human-confirm gate on a PAUSED run. `approve=true` proceeds (optionally applying
   * `amend` to the next unit's instruction); `approve=false` rejects → cancels the run. Resolves
   * to the resulting status token. Rejects if the run is not paused at a gate.
   */
  confirmGate(runId: string, approve: boolean, amend?: string | undefined | null): Promise<string>
  /**
   * Cancel a run — mark it terminally `Cancelled` and stop advancing it. Resolves to the status
   * token. Safe whether the run is executing or paused.
   */
  cancelRun(runId: string): Promise<string>
  /**
   * Resolve a pending ACP elicitation. `action` must be `"accept"`, `"decline"`, or `"cancel"`;
   * `response` is the human's typed/selected value as a JSON-typed value — pass `null` for
   * `decline`/`cancel`. Resolves to `"ok"` on success, rejects if no matching elicitation exists.
   */
  resolveElicitation(runId: string, elicitationId: string, action: string, response?: any | undefined | null): Promise<string>
  /**
   * Validate + launch a campaign — a DAG of Runs (DES-CAMPAIGN-001). `defJson` is a
   * `CampaignDef` JSON object in the engine wire shape (snake_case): `{ id, name?, nodes:
   * [{ node_id, run_spec: { problem, clis, entity_mode, human_confirm?, repo_ref?,
   * workflow_id? } }], edges?: [{ from, to, condition? }], policy?, max_concurrency }`.
   * Resolves to the campaign id. Fire-and-forget: independent nodes dispatch immediately and
   * progress arrives as the `campaign*` CoreEvents — `subscribe()` first. Rejects a cycle /
   * empty / duplicate-edge / unknown-edge-endpoint def at launch, before anything persists.
   */
  launchCampaign(defJson: string): Promise<string>
  /**
   * Resume a campaign from its persisted state (after a pause, crash, or a fresh process) —
   * the scheduler re-derives the ready set from the persisted node statuses and re-attaches
   * any mid-run node, never re-running a completed node. Resolves to the campaign status
   * token (`running` | `paused` | `completed` | `partially_completed` | `failed` |
   * `cancelled`); rejects for an unknown id.
   */
  resumeCampaign(id: string): Promise<string>
  /**
   * Cancel a campaign — cancel every in-flight node's Run and mark the rest `Cancelled`.
   * Resolves to the campaign status token; rejects for an unknown id.
   */
  cancelCampaign(id: string): Promise<string>
  /**
   * A campaign's full state — the DAG (embedded def), per-node statuses, per-node run ids and
   * attempt counters — as a JSON `Campaign` object (engine wire shape, snake_case), or the
   * JSON literal `null` when the id is unknown. The read a DAG/scoreboard view builds from.
   */
  campaignDetail(id: string): Promise<string>
  /**
   * Every campaign on the store, as a JSON array of `Campaign` objects. Read-only store
   * connection (the `project_list` pattern) — the single-writer actor is not involved, so a
   * long campaign list cannot queue behind dispatch work.
   */
  campaignList(): Promise<string>
  /** The agent session ids currently on the store, as a JSON array of strings. */
  sessions(): Promise<string>
  /**
   * Every session + its ordered units, as a JSON array of `{ session, units }` objects (the read
   * a UI builds its project list from).
   */
  sessionsDetail(): Promise<string>
  /** A unit's captured work output (transcript), as a JSON value — a string, or `null` if none. */
  workOutput(unitId: string): Promise<string>
  /**
   * A run's recorded event history, oldest first, as a JSON array. Each entry is the SAME tagged
   * object the `/ws` stream carries ([`CoreEvent::to_json`]) plus a capture-time `ts` (epoch millis)
   * and an ordering `seq`.
   *
   * The read half of FINDING-014: an evidence bundle assembled after a run must read what actually
   * happened rather than re-derive pseudo-events from unit records, which cannot recover what it
   * never saw and invents its own type names doing it. Because the log and the socket serialize
   * through one mapping, an event named here is the event named live.
   *
   * Empty array for an unknown run, one that emitted nothing, or one predating the log — an absent
   * history is not an error. Streaming chunk events (`cliOutputDelta`, `chatDelta`,
   * `terminalOutput`, `heartbeat`) are excluded by design.
   */
  runEvents(runId: string): Promise<string>
  /**
   * Register a git repository the orchestrator can run within. Validates it is a git repo with
   * ≥1 commit; resolves to the persisted `RepoEntry` as a JSON object.
   */
  registerRepo(name: string, rootPath: string): Promise<string>
  /** List every registered repository, as a JSON array of `RepoEntry` objects. */
  listRepos(): Promise<string>
  /**
   * Create a project. Resolves to the persisted `Project` as a JSON object
   * (`{ id, name, description, status, scope, created_at, updated_at }`). Rejects on an
   * empty/overlong name or a name already used by an ACTIVE project (the API's 409).
   */
  projectCreate(name: string, description?: string | undefined | null): Promise<string>
  /**
   * Rename / describe / archive / restore a project (`status`: `active` | `archived`;
   * `description: ""` clears it). Resolves to the updated `Project` JSON. Rejects for the
   * synthesized `default` project or an unknown id.
   */
  projectUpdate(id: string, name?: string | undefined | null, description?: string | undefined | null, status?: string | undefined | null): Promise<string>
  /**
   * Every project on the store (all statuses — the caller filters), newest first, as a JSON
   * array of `Project` objects. The synthesized `default` project is an API-layer concept and
   * is NOT in this list.
   */
  projectList(): Promise<string>
  /** One project by id, as a JSON `Project` object — or the JSON literal `null` when unknown. */
  projectGet(id: string): Promise<string>
  /**
   * The LIVE members of a project, oldest attach first, as a JSON array of `ProjectMember`
   * objects (`{ id, project_id, member_kind, member_ref, meta, attached_at, attached_by }`).
   */
  projectMembers(projectId: string): Promise<string>
  /**
   * Attach a member (`memberKind` is the open `<product>.<noun>` grammar, e.g. `crew.run`,
   * `interactive.doc`; `metaJson` is opaque JSON text; `attachedBy` ∈ studio|interactive|cli|api).
   * Idempotent on `(project, kind, ref)`. Resolves to `{ "member": ProjectMember, "created":
   * boolean }` — emit the membership.attached event only when `created` is true.
   */
  projectMemberAttach(projectId: string, memberKind: string, memberRef: string, metaJson?: string | undefined | null, attachedBy?: string | undefined | null): Promise<string>
  /**
   * Detach a member. Resolves to `"true"` when a live membership was removed, `"false"` when
   * no such live member exists on that project (the caller answers 404). Detaching never
   * touches the member's own data (the run, the doc dir).
   */
  projectMemberDetach(projectId: string, memberId: string): Promise<string>
  /**
   * The project ids holding a live membership for `(memberKind, memberRef)` — the reverse read
   * (run → projects) the daemon uses to tag frames and synthesize the `default` project. JSON
   * array of strings.
   */
  memberProjects(memberKind: string, memberRef: string): Promise<string>
  /**
   * Durable interaction requests (DES-PROJECT-001 §5.3), newest first, optionally filtered by
   * run and/or status (`open` | `answered` | `expired` | `cancelled`). JSON array of
   * `{ id, session_id, kind, ord, reviewing_ord, prompt, status, answer, created_at,
   * resolved_at }`. This is the durable truth the daemon's gate/elicitation caches demote to
   * latency layers over — it survives a daemon restart because the actor wrote it in the same
   * batch as the run's `awaiting_human` transition.
   */
  interactionRequests(sessionId?: string | undefined | null, status?: string | undefined | null): Promise<string>
  /**
   * Capture an episodic memory at `scope` (STRICT `kind:id[/kind:id...]` path; `""` = root —
   * a malformed segment REJECTS rather than silently re-rooting). Resolves to `"ok"`.
   */
  captureMemory(content: string, scope: string): Promise<string>
  /**
   * LIST memories within `scope`'s subtree (strict path; `""` = all), newest first, up to
   * `limit`. JSON array of `{ content, score, tier }`. `listMemories("project:<id>", …).length
   * > 0` is the cheap "does this project have a record?" probe (the ADR's memory.coverage).
   */
  listMemories(scope: string, limit: number): Promise<string>
  /**
   * Ingest a document (title + chunks) into the knowledge store. `chunksJson` is a JSON array
   * of strings. Resolves to the ingested chunk count as a JSON number.
   */
  ingestKnowledge(title: string, chunksJson: string): Promise<string>
  /**
   * Recall up to `k` knowledge chunks relevant to `query`. JSON array of
   * `{ content, score, source }`.
   */
  recallKnowledge(query: string, k: number): Promise<string>
  /** All registered governance policies, as a JSON array of `Policy` objects. */
  listPolicies(): Promise<string>
  /**
   * All conformance rules on the store (Pattern + Policy types), as a JSON array of
   * serialized `ConformanceRule` objects — severity-first (critical→info), then weight DESC
   * within a band, then id. The rows carry the unified steering-rule model's fields
   * (steering_type / applies_to / excludes / weight / effect / trigger / obligations /
   * criteria / provenance / …) exactly as the model serializes them — default-valued steering
   * fields are elided on the wire (absent steering_type ⇒ "architecture", absent weight ⇒ 1).
   *
   * Steering facets (the studio Steering surface's list):
   * - `steeringType` filters on the rule's `steering_type` — one of architecture | development |
   *   security | testing | operations | compliance | design-ux. A rule authored before the
   *   field existed counts as `"architecture"` (the model's serde default); an unknown value
   *   REJECTS (fails closed — a typo must not read as "no rules of that type").
   * - `includeRetired: true` adds withdrawn rules (retire-not-delete: they still explain the
   *   past decisions that cite them; recall/enforcement never returns them).
   *
   * Both omitted ⇒ the exact pre-0.7.5 behavior (every active rule).
   */
  listConformanceRules(steeringType?: string | undefined | null, includeRetired?: boolean | undefined | null): Promise<string>
  /**
   * The doctrine RuleSet parents (AW-13 grouping) as a JSON array of
   * `{ domain, rule_ids, rule_count }` rows, domain-sorted. The array length is the wiki
   * meta's `ruleset_count` (crew's `countRuleSets` resolved `null` on engine builds without
   * this binding — "cannot count" must never impersonate "0"); the rows carry `Contains`
   * membership so grouping renders without a second round-trip. Membership is the store's
   * edges verbatim — a retired rule stays listed in its RuleSet (grouping is doc structure,
   * not enforcement). Read-only connection; never blocks the single-writer actor.
   */
  listRuleSets(): Promise<string>
  /** All conformance claims (governance decisions) on the store, as a JSON array. */
  listConformanceClaims(): Promise<string>
  /**
   * The AW-23 / arch-R23 population/connection scoreboard — the wiki-health report that tells
   * a POPULATED rule corpus from an ingested-once-and-decaying one: rule counts, typing
   * coverage, connection (ref-resolution) coverage, enforcement evidence, recall volume.
   * Resolves to the SAME JSON `wicked-core rules scoreboard --json` emits (a pretty-printed
   * `Scoreboard` object) — one report shape for CLI operators and crew/studio consumers alike.
   *
   * `docsDir` mirrors the CLI's `--dir`: typing coverage is doc-side (`enforcement_class`
   * lives in frontmatter, never on the rule node), so it needs the SAME docs root
   * `rules ingest --dir` used; omit it and the report says `typing.available: false`,
   * honestly, in-band — never a fake 0% or 100%. `ambiguityCap` mirrors `--ambiguity-cap`
   * (default 5; must be ≥ 1 — fails closed on 0, like the CLI). Strictly a REPORT over a
   * read-only connection: it never blocks the single-writer actor, and residue gating stays
   * `rules drift`'s job.
   */
  governanceScoreboard(docsDir?: string | undefined | null, ambiguityCap?: number | undefined | null): Promise<string>
  /**
   * Upsert a governance policy. `policy_json` is a JSON-serialized `Policy` object
   * (fields: id, kind, applies_to, effect, trigger, severity, criteria, rule, obligations).
   * Validates server-side (fails closed on deny_unknown_fields + required fields). Idempotent
   * on stable id — calling twice with the same id and payload is a no-op.
   */
  upsertPolicy(policyJson: string): Promise<string>
  /**
   * Upsert a conformance rule. `rule_json` is a JSON-serialized `ConformanceRule` object
   * (fields: id, rule_type, statement, severity, confidence, targets, provenance — plus the
   * unified steering-rule fields: steering_type, applies_to, excludes, weight, and the
   * optional effect / trigger / obligations / criteria; a rule without `effect` stays
   * recall-only). The JSON passes through un-projected — the model's own serde is the wire
   * contract, so new steering fields ride this binding without a rebuild. Provenance is
   * first-class for UI/chat-authored rules too (`provenance.source: "ui" | "chat"`), not just
   * doc-ingested `path@sha#id` rows. Validates server-side (INV-C1/C2/C4). Idempotent on
   * stable id.
   */
  upsertConformanceRule(ruleJson: string): Promise<string>
  /**
   * STEERING batch import (the unified steering-rule model). `batch_json` is a JSON
   * `{ default_type: string | null, entries: [...] }` document where each entry is either a
   * frontmattered markdown doc (`{ kind: "doc", name?, content }` — parsed by the SAME
   * MarkdownAdapter/normalize path `rules ingest --dir` runs, provenance `path@sha#id` refs
   * included) or a ready rule object (`{ kind: "rule", rule }` — the rule JSON passes to the
   * upsert path un-projected, so new model fields ride through without a rebuild).
   * `default_type` is applied as the `steering_type` of every rule whose entry omits one; a
   * rule that names its own type keeps it.
   *
   * Fail-closed PER ENTRY: a bad entry (unparseable doc, invalid rule, INV violation,
   * duplicate id within the batch) rejects ALONE with its reason — the rest still land; only
   * a malformed batch envelope rejects the whole call. Every write goes through the
   * single-writer actor (validate + `register_rule`). Resolves to a JSON array of per-entry
   * results, batch order: `{ index, name?, status: "imported" | "rejected", ids?, error? }`
   * (`ids` = the rule ids the entry minted — a doc can mint several; a rejected entry mints
   * none). This binding is also crew's PRESENCE SENTINEL for the whole steering seam
   * (`steeringSupported()`): it ships with the unified model, so its existence tells crew the
   * engine round-trips the steering fields instead of silently dropping them.
   */
  steeringImport(batchJson: string): Promise<string>
  /**
   * Governance rules eval — run an eval corpus through the REAL SELECT→DECIDE gate path and
   * score every sample (the engine seam behind crew's `POST /api/v1/testing/evals/run`).
   * `args_json` is `{ type?, corpus?, knowledgeDb?, dbPath }` (camelCase keys are the PINNED
   * binding contract): `type` slices the corpus to one of the 7 steering types; `corpus`
   * names an estate knowledge scope (`evals:<name>` — a corpus landed by
   * [`Core::governance_corpus_import`]) or, omitted, selects the compiled-in default corpus;
   * `knowledgeDb` powers embedding gap hints (absent/unusable ⇒ the report carries
   * `degraded: "facet-only"` — an honest downgrade to keyword hints, never fabricated
   * similarity); `dbPath` is the rules store, opened READ-ONLY — this call never goes through
   * the single-writer actor and never writes either store.
   *
   * Resolves to the `EvalReport` JSON exactly as the engine serializes it (snake_case — crew
   * passes it through verbatim as the pinned wire contract):
   * `{ results: [{ sample: { id, description, kind, steering_type }, expected: "deny"|"allow",
   * fired: [rule-id…], verdict: "caught"|"gap"|"false_positive", nearest_rules? }],
   * summary: { total, caught, gaps, false_positives }, degraded: "facet-only"|null }`.
   *
   * Fail-closed: malformed args, an unknown steering type, a corpus name outside the
   * `evals:` scope, or a missing store reject the Promise with the engine's reason — crew maps
   * those to 400, and gates the whole route on this binding's PRESENCE (absent ⇒ 501).
   */
  governanceEvals(argsJson: string): Promise<string>
  /**
   * Import an eval corpus into the estate knowledge store (the engine seam behind crew's
   * `POST /api/v1/testing/corpora/import`). `args_json` is `{ name, samples, knowledgeDb? }`
   * (camelCase keys are the PINNED binding contract): `samples` is an array of
   * `{ id, description, kind: "good"|"bad", steering_type, signals: { phase?, tool?, files?,
   * content? } }` — validated fail-closed as a whole corpus (blank/duplicate ids, unknown
   * steering types reject the batch) and landed under scope `evals:<name>`, one chunk per
   * sample, id-keyed (re-import upserts in place) WITH embeddings via the same
   * `KnowledgeEngine` path the rules fan-out uses. `knowledgeDb` defaults to the operator's
   * `~/.wicked-estate/knowledge.db`; tests must always pass a temp path.
   *
   * Resolves to the `ImportReceipt` JSON `{ imported, scope: "evals:<name>", embedded }` —
   * `embedded` is VERIFIED against the durable store after the write handle drops, not
   * asserted. Fail-closed on malformed args (crew maps that to 400; route presence-gates on
   * this binding like [`Core::governance_evals`] — absent ⇒ 501).
   */
  governanceCorpusImport(argsJson: string): Promise<string>
  /**
   * Withdraw a governance policy from enforcement (FINDING-038 — governance state was otherwise
   * append-only, so a mis-authored policy denied forever).
   *
   * Retire, not delete: the node stays readable so a past decision citing this id can still be
   * explained, but SELECT stops returning it, so it can never decide another gate.
   *
   * Resolves to a JSON-encoded boolean: the four characters `true` if a policy with that id
   * existed, the five characters `false` if none did. Like every method here it hands JS a
   * `Promise<string>` carrying JSON, so it must be `JSON.parse`d — a bare truthiness test
   * passes on BOTH values and would read a miss as a hit, losing exactly the 200-vs-404
   * distinction this return value exists to carry.
   */
  retirePolicy(id: string): Promise<string>
  /**
   * Archive (or unarchive) a TERMINAL run (crew#265) — a write-off, not a delete: the run and
   * its artifacts stay fully readable, but default run listings exclude it. Resolves to a
   * JSON-encoded boolean (`true` = session existed, `false` = unknown id → answer 404); REJECTS
   * when the run is non-terminal (the caller answers 409 — write-off is for finished history
   * only). Parse the reply; a bare truthiness test reads a miss as a hit.
   */
  archiveRun(runId: string, archived: boolean, note?: string | undefined | null): Promise<string>
  /**
   * Withdraw a conformance rule from recall. Same retire-not-delete contract as
   * [`Core::retire_policy`], and the same JSON-encoded `true`/`false` reply that must be
   * parsed rather than tested for truthiness.
   */
  retireConformanceRule(id: string): Promise<string>
  /**
   * Register (or replace) a workflow definition in the actor's runtime registry. `json` is a
   * JSON-serialised `WorkflowDef` object (fields: id, description, phases — see the wicked-core
   * workflow schema). Validates server-side (id + ≥1 phase required); rejects invalid JSON or a
   * structurally invalid def. Returns the registered workflow id. Idempotent on id — calling
   * twice replaces the first registration. The def is immediately visible to the next `launchRun`
   * call; no process restart required.
   */
  registerWorkflow(json: string): Promise<string>
  /**
   * Recall which conformance rules apply to the given `query_json` (a JSON-serialized
   * `RuleQuery` — fields: language, layer, framework, severity, rule_type, steering_type;
   * all optional).
   * An empty or whitespace `query_json` is treated as an all-rules query (no facet filters).
   * Opens a read-only connection — does not block the single-writer actor. Returns a JSON
   * array of `ConformanceRule` objects, severity-first then id.
   */
  recallRulesPreview(queryJson: string): Promise<string>
  /**
   * Front-half coverage gate report — JSON-serialized `CoverageReport`, or the JSON literal
   * `null` when the store has no domain-model nodes yet. Opens a read-only connection so it
   * never blocks the single-writer actor.
   */
  getCoverageReport(): Promise<string>
  /**
   * Coverage for ONE registered repo, computed over that repo's OWN code graph — not the daemon's
   * bookkeeping store (FINDING-009). `get_coverage_report` above reads `self.db_path` (the daemon
   * `core.db`), which holds run/governance nodes but none of a repo's domain/requirement nodes, so
   * it reports a vacuous `coverage: 1.0` over an empty denominator and cannot name a repo. This
   * resolves the repo from the registry, opens its `code_graph_db` (the engine-resolved path
   * every consumer shares — the legacy in-tree `<root>/.codegraph/estate.db` for a repo that
   * already has one, else the estate home's `<estate_root>/<key>/estate.db`; see wicked-core's
   * `code_graph.rs` ADR), and recomputes over it. An unknown `repo_ref` is an
   * ERROR, never a silent vacuous report — the caller must name a real repo.
   * Resolves to the coverage report as a JSON string (`ts_return_type` pins it — the crew adapter
   * used to cast away an `unknown` here; #225 review).
   */
  getCoverageReportForRepo(repoRef: string): Promise<string>
  /**
   * Node-count-by-kind summary of ONE registered repo's code graph, over that repo's OWN store
   * (#122). Resolves to a JSON string: an array of `{ "kind": string, "count": number }`,
   * kind-sorted. An unknown `repo_ref` REJECTS — never a silent empty summary.
   */
  getGraphKindsForRepo(repoRef: string): Promise<string>
  /**
   * Open a PTY terminal session running `cmd` (or the login shell if omitted) in `cwd`, sized
   * `cols`x`rows`. `governed=false` is a loud, opt-in UNGOVERNED operator shell that bypasses the
   * gate-hook (DES §7); pass `true` for the governed default. Resolves the new terminal id. Output
   * arrives as `terminalOutput` events, so `subscribe()` FIRST to catch `terminalOpened` + bytes.
   */
  openTerminal(cwd: string, cmd: Array<string> | undefined | null, cols: number, rows: number, governed: boolean): Promise<string>
  /**
   * Write raw input bytes (keystrokes) to a terminal. The `bytes` Buffer is copied to an owned
   * `Vec<u8>` on the Node thread (a cheap memcpy — keystroke payloads are tiny) so the blocking
   * write can run off-thread without moving a JS-owned Buffer across threads. Resolves `"ok"`;
   * rejects if the terminal id is unknown or the write fails.
   */
  writeTerminal(id: string, bytes: Buffer): Promise<string>
  /**
   * Resize a terminal's PTY to `cols`x`rows`. Resolves `"ok"`; rejects if the terminal id is
   * unknown or the resize fails.
   */
  resizeTerminal(id: string, cols: number, rows: number): Promise<string>
  /**
   * Close a terminal: the actor kills the child, joins the reader thread, and drops the registry +
   * I/O entries (no orphaned process/thread). Resolves `"ok"` once teardown completes; a
   * `terminalExited` event is emitted. Rejects on an unknown id.
   */
  closeTerminal(id: string): Promise<string>
  /**
   * Inject an operator message into one or all active PTY workers for a run.
   *
   * `target` is either `"all"` (write to every PTY session for the run) or a CLI key string
   * (write only to that CLI's session). ACP-backed sessions have no PTY and are skipped with a
   * warning. Fires [`CoreEvent::WorkerMessageInjected`] for each successful write.
   */
  injectWorkerMessage(runId: string, message: string, target: string): Promise<unknown>
  /**
   * Stop the current worker for `ord` in run `run_id` and re-dispatch it.
   *
   * `newCli` is either a CLI key string (re-dispatch immediately to that CLI) or `null` (re-run
   * the council and let it pick). Returns `"ok"` when the command has been queued; the
   * [`CoreEvent::UnitReassigned`] event confirms the reassignment.
   */
  reassignUnit(runId: string, ord: number, newCli?: string | undefined | null): Promise<unknown>
}
/**
 * A live event subscription returned by [`Core::subscribe`]. Owns the FIFO pump thread + its
 * [`ThreadsafeFunction`]. `close()` / `unsubscribe()` tears both down deterministically (set the
 * stop flag → join the pump, which drops the event `Receiver` so the actor prunes its sender →
 * abort the tsfn). Idempotent; dropping the JS handle without an explicit close also stops the pump.
 */
export declare class Subscription {
  /**
   * Stop delivering events and release the pump thread + `ThreadsafeFunction`. Idempotent and
   * safe on a normal shutdown path; after it returns the pump is joined and the tsfn aborted, so
   * the callback will not fire again. This is the teardown that makes re-subscribe leak-free and
   * lets a plain `main()` return promptly.
   */
  close(): void
  /** Alias for [`Subscription::close`]. */
  unsubscribe(): void
}

// ─── hand-authored (not napi-generated): see scripts/finalize-dts.mjs ───
/**
 * A CoreEvent, delivered as a JSON string to the {@link Core.subscribe} callback. Discriminated on
 * `type`. Fields vary by variant (see wicked-core `CoreEvent`): e.g.
 * `sessionStarted` `{session, problem}`, `unitPlanned` `{session, ord, description}`,
 * `unitDistributed` `{session, ord, cli}`, `awaitingHuman` `{session, ord, prompt}`,
 * `gateDecided` `{session, ord, allow}`, `unitDone`/`unitExecuting`/`resumed` `{session, ord}`,
 * `sessionCompleted` `{session}`, `sessionFailed` `{session, ord}`, `error` `{session, message}`.
 * PTY terminal sessions emit `terminalOpened` `{id, cwd}`, `terminalOutput` `{id, seq, bytesB64}`
 * (raw output base64-encoded in `bytesB64`), and `terminalExited` `{id, status}`.
 */
export interface CoreEventJson {
  type: string
  session?: string
  ord?: number
  [k: string]: unknown
}
// ─── end hand-authored ───
